### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by krisfans** [alan-w-255/telescope-mru.nvim#1]
Thank you for creating this mru extension for telescope.nvim. But how to use it?
This is my config but it doesn't work.
```lua
require("telescope").load_extension("mru")
```

**Comment by alan-w-255** [comment]
need to install and load plugin `yegappan/mru` first.

**Comment by krisfans** [comment]
Thanks! I think add  this into README would be better.

> need to install and load plugin `yegappan/mru` first.
